### ISSUE TITLE
SPIKE Look for most optimal solution for backend

### ISSUE THREAD

**Issue by hoffmannjan** [casper-network/casper-blockexplorer-middleware#69]
Assuming we're using NestJS this will be probably [this](https://www.npmjs.com/package/@nestjs/websockets) and [this](https://www.npmjs.com/package/@nestjs/websockets) but please make sure its a good fit :)

**Comment by hoffmannjan** [comment]
depending on the outcome please add another tickets to this epic

**Comment by mgibson-casper** [comment]
It has been determined that we will be able to implement web sockets in the middleware using the NestJS websockets library out of the box. Tickets to follow.
